// <auto-generated />
using System;
using DepVis.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepVis.Core.Migrations
{
    [DbContext(typeof(DepVisDbContext))]
    [Migration("20251005193603_MakeRecommendationNullable")]
    partial class MakeRecommendationNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DepVis.Shared.Model.PackageDependency", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ParentId", "ChildId");

                    b.HasIndex("ChildId");

                    b.ToTable("PackageDependencies");
                });

            modelBuilder.Entity("DepVis.Shared.Model.PackageVulnerability", b =>
                {
                    b.Property<Guid>("SbomPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VulnerabilityId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SbomPackageId", "VulnerabilityId");

                    b.HasIndex("VulnerabilityId");

                    b.ToTable("PackageVulnerabilities");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DepVis.Shared.Model.ProjectBranches", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsTag")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageCount")
                        .HasColumnType("int");

                    b.Property<int>("ProcessStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProcessStep")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VulnerabilityCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectBranches");
                });

            modelBuilder.Entity("DepVis.Shared.Model.ProjectStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PackageCount")
                        .HasColumnType("int");

                    b.Property<int>("VulnerabilityCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProjectStatistics");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Sbom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectBranchId");

                    b.ToTable("Sboms");
                });

            modelBuilder.Entity("DepVis.Shared.Model.SbomPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BomRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ecosystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SbomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SbomId");

                    b.ToTable("SbomPackages");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Vulnerability", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("SbomPackageVulnerability", b =>
                {
                    b.Property<Guid>("AffectedPackagesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VulnerabilitiesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AffectedPackagesId", "VulnerabilitiesId");

                    b.HasIndex("VulnerabilitiesId");

                    b.ToTable("SbomPackageVulnerability");
                });

            modelBuilder.Entity("DepVis.Shared.Model.PackageDependency", b =>
                {
                    b.HasOne("DepVis.Shared.Model.SbomPackage", "Child")
                        .WithMany("Parents")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DepVis.Shared.Model.SbomPackage", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DepVis.Shared.Model.PackageVulnerability", b =>
                {
                    b.HasOne("DepVis.Shared.Model.SbomPackage", "Package")
                        .WithMany()
                        .HasForeignKey("SbomPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepVis.Shared.Model.Vulnerability", "Vulnerability")
                        .WithMany()
                        .HasForeignKey("VulnerabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Vulnerability");
                });

            modelBuilder.Entity("DepVis.Shared.Model.ProjectBranches", b =>
                {
                    b.HasOne("DepVis.Shared.Model.Project", "Project")
                        .WithMany("ProjectBranches")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Sbom", b =>
                {
                    b.HasOne("DepVis.Shared.Model.ProjectBranches", "ProjectBranch")
                        .WithMany("Sboms")
                        .HasForeignKey("ProjectBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectBranch");
                });

            modelBuilder.Entity("DepVis.Shared.Model.SbomPackage", b =>
                {
                    b.HasOne("DepVis.Shared.Model.Sbom", "Sbom")
                        .WithMany("SbomPackages")
                        .HasForeignKey("SbomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sbom");
                });

            modelBuilder.Entity("SbomPackageVulnerability", b =>
                {
                    b.HasOne("DepVis.Shared.Model.SbomPackage", null)
                        .WithMany()
                        .HasForeignKey("AffectedPackagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepVis.Shared.Model.Vulnerability", null)
                        .WithMany()
                        .HasForeignKey("VulnerabilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DepVis.Shared.Model.Project", b =>
                {
                    b.Navigation("ProjectBranches");
                });

            modelBuilder.Entity("DepVis.Shared.Model.ProjectBranches", b =>
                {
                    b.Navigation("Sboms");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Sbom", b =>
                {
                    b.Navigation("SbomPackages");
                });

            modelBuilder.Entity("DepVis.Shared.Model.SbomPackage", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Parents");
                });
#pragma warning restore 612, 618
        }
    }
}
