// <auto-generated />
using System;
using DepVis.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepVis.Core.Migrations
{
    [DbContext(typeof(DepVisDbContext))]
    [Migration("20260424195732_sboms1t1")]
    partial class sboms1t1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CWEVulnerability", b =>
                {
                    b.Property<Guid>("CWESId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VulnerabilitiesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CWESId", "VulnerabilitiesId");

                    b.HasIndex("VulnerabilitiesId");

                    b.ToTable("VulnerabilityCWEs", (string)null);
                });

            modelBuilder.Entity("DepVis.Shared.Model.BranchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommitMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectVulnerabilityCount")
                        .HasColumnType("int");

                    b.Property<int>("PackageCount")
                        .HasColumnType("int");

                    b.Property<int>("ProcessState")
                        .HasColumnType("int");

                    b.Property<int>("ProcessStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VulnerabilityCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectBranchId", "ProcessState")
                        .HasDatabaseName("IX_BranchHistories_ProjectBranchId_ProcessState");

                    b.HasIndex("ProjectBranchId", "ProcessStatus")
                        .HasDatabaseName("IX_BranchHistories_ProjectBranchId_ProcessStatus");

                    b.ToTable("BranchHistories");
                });

            modelBuilder.Entity("DepVis.Shared.Model.CWE", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CweId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("CWEs");
                });

            modelBuilder.Entity("DepVis.Shared.Model.PackageDependency", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ParentId", "ChildId");

                    b.HasIndex("ChildId");

                    b.ToTable("PackageDependencies");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DepVis.Shared.Model.ProjectBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommitMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HistoryProcessinStatus")
                        .HasColumnType("int");

                    b.Property<int>("HistoryProcessingStep")
                        .HasColumnType("int");

                    b.Property<bool>("IsTag")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PackageCount")
                        .HasColumnType("int");

                    b.Property<int>("ProcessStatus")
                        .HasColumnType("int");

                    b.Property<int>("ProcessStep")
                        .HasColumnType("int");

                    b.Property<int>("ProcessedHistoryCommits")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalHistoryCommits")
                        .HasColumnType("int");

                    b.Property<int>("VulnerabilityCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .HasDatabaseName("IX_ProjectBranches_ProjectId_Name");

                    b.ToTable("ProjectBranches");
                });

            modelBuilder.Entity("DepVis.Shared.Model.ProjectStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EcoSystems")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VulnerabilityCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ProjectStatistics");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Reference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VulnerabilityId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VulnerabilityId");

                    b.ToTable("References");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Sbom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommitMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectBranchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchHistoryId")
                        .IsUnique()
                        .HasFilter("[BranchHistoryId] IS NOT NULL");

                    b.HasIndex("CommitSha")
                        .HasDatabaseName("IX_Sbom_CommitSha");

                    b.HasIndex("ProjectBranchId")
                        .IsUnique()
                        .HasFilter("[ProjectBranchId] IS NOT NULL");

                    b.HasIndex("BranchHistoryId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Sboms_BranchHistoryId_CreatedAt");

                    b.HasIndex("ProjectBranchId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Sboms_ProjectBranchId_CreatedAt");

                    b.ToTable("Sboms");
                });

            modelBuilder.Entity("DepVis.Shared.Model.SbomPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BomRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Depth")
                        .HasColumnType("int");

                    b.Property<string>("Ecosystem")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PackageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SbomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SbomId");

                    b.HasIndex("Ecosystem", "Name", "Version")
                        .HasDatabaseName("IX_SbomPackage_Ecosystem_Name_Version");

                    b.ToTable("SbomPackages");
                });

            modelBuilder.Entity("DepVis.Shared.Model.SbomPackageVulnerability", b =>
                {
                    b.Property<Guid>("SbomPackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VulnerabilityId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SbomPackageId", "VulnerabilityId");

                    b.HasIndex("VulnerabilityId");

                    b.ToTable("SbomPackageVulnerabilities", (string)null);
                });

            modelBuilder.Entity("DepVis.Shared.Model.Vulnerability", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("CWEVulnerability", b =>
                {
                    b.HasOne("DepVis.Shared.Model.CWE", null)
                        .WithMany()
                        .HasForeignKey("CWESId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepVis.Shared.Model.Vulnerability", null)
                        .WithMany()
                        .HasForeignKey("VulnerabilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DepVis.Shared.Model.BranchHistory", b =>
                {
                    b.HasOne("DepVis.Shared.Model.ProjectBranch", "ProjectBranch")
                        .WithMany("BranchHistories")
                        .HasForeignKey("ProjectBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectBranch");
                });

            modelBuilder.Entity("DepVis.Shared.Model.PackageDependency", b =>
                {
                    b.HasOne("DepVis.Shared.Model.SbomPackage", "Child")
                        .WithMany("Parents")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DepVis.Shared.Model.SbomPackage", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("DepVis.Shared.Model.ProjectBranch", b =>
                {
                    b.HasOne("DepVis.Shared.Model.Project", "Project")
                        .WithMany("ProjectBranches")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DepVis.Shared.Model.ProjectStatistics", b =>
                {
                    b.HasOne("DepVis.Shared.Model.Project", "Project")
                        .WithOne("ProjectStatistics")
                        .HasForeignKey("DepVis.Shared.Model.ProjectStatistics", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Reference", b =>
                {
                    b.HasOne("DepVis.Shared.Model.Vulnerability", null)
                        .WithMany("References")
                        .HasForeignKey("VulnerabilityId");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Sbom", b =>
                {
                    b.HasOne("DepVis.Shared.Model.BranchHistory", "BranchHistory")
                        .WithOne("Sbom")
                        .HasForeignKey("DepVis.Shared.Model.Sbom", "BranchHistoryId");

                    b.HasOne("DepVis.Shared.Model.ProjectBranch", "ProjectBranch")
                        .WithOne("Sbom")
                        .HasForeignKey("DepVis.Shared.Model.Sbom", "ProjectBranchId");

                    b.Navigation("BranchHistory");

                    b.Navigation("ProjectBranch");
                });

            modelBuilder.Entity("DepVis.Shared.Model.SbomPackage", b =>
                {
                    b.HasOne("DepVis.Shared.Model.Sbom", "Sbom")
                        .WithMany("SbomPackages")
                        .HasForeignKey("SbomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sbom");
                });

            modelBuilder.Entity("DepVis.Shared.Model.SbomPackageVulnerability", b =>
                {
                    b.HasOne("DepVis.Shared.Model.SbomPackage", "SbomPackage")
                        .WithMany("SbomPackageVulnerabilities")
                        .HasForeignKey("SbomPackageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DepVis.Shared.Model.Vulnerability", "Vulnerability")
                        .WithMany("SbomPackageVulnerabilities")
                        .HasForeignKey("VulnerabilityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SbomPackage");

                    b.Navigation("Vulnerability");
                });

            modelBuilder.Entity("DepVis.Shared.Model.BranchHistory", b =>
                {
                    b.Navigation("Sbom");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Project", b =>
                {
                    b.Navigation("ProjectBranches");

                    b.Navigation("ProjectStatistics");
                });

            modelBuilder.Entity("DepVis.Shared.Model.ProjectBranch", b =>
                {
                    b.Navigation("BranchHistories");

                    b.Navigation("Sbom");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Sbom", b =>
                {
                    b.Navigation("SbomPackages");
                });

            modelBuilder.Entity("DepVis.Shared.Model.SbomPackage", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Parents");

                    b.Navigation("SbomPackageVulnerabilities");
                });

            modelBuilder.Entity("DepVis.Shared.Model.Vulnerability", b =>
                {
                    b.Navigation("References");

                    b.Navigation("SbomPackageVulnerabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
